sudo: required
services:
  - docker

before_install:
  - docker build -t austynyou/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true austynyou/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Docker-react-env-2"
  bucket_name: "elasticbeanstalk-us-west-1-985733944810"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"